import React, { useState } from 'react';
import {
  Globe,
  Activity,
  Target,
  Lightbulb,
  Copy,
  Check,
  Share2,
  FileText,
  Send
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import toast from 'react-hot-toast';

interface Props {
  raw: string;
  token: string;
}

export const ProAnalysisViewer: React.FC<Props> = ({ raw, token }) => {
  const [copied, setCopied] = useState(false);
  const [sharing, setSharing] = useState(false);
  const { userProfile } = useAuth();

  // Parse sections using regex with normalization for LLM formatting quirks
  const parseSection = (tag: string) => {
    // Normalize: **#TAG#** -> #TAG#, ## #TAG# -> #TAG#
    const normalized = raw
      .replace(/\*\*#([A-Z]+)#\*\*/g, '#$1#') // Remove bold
      .replace(/##\s*#?([A-Z]+)#?/g, (match, p1) => `#${p1}#`); // Handle headers

    const regex = new RegExp(`#${tag}#\\s*([\\s\\S]*?)(?=#|$)`, 'i');
    const match = normalized.match(regex);
    return match ? match[1].trim() : null;
  };

  const ctxt = parseSection('CTXT');
  const ta = parseSection('TA');
  const plan = parseSection('PLAN');
  const insight = parseSection('INSIGHT');

  // Extract params specifically
  const entry = raw.match(/Entry:\s*([\d.]+)/i)?.[1];
  const tp = raw.match(/TP:\s*([\d.]+)/i)?.[1];
  const sl = raw.match(/SL:\s*([\d.]+)/i)?.[1];

  const getShareText = () => {
    return `INSTITUTIONAL REPORT: ${token}\n\n` +
      `CONTEXT\n${ctxt || 'N/A'}\n\n` +
      `TECHNICALS\n${ta || 'N/A'}\n\n` +
      `INSIGHT\n${insight || 'N/A'}\n\n` +
      `PLAN\n${plan || 'N/A'}\n\n` +
      `--------\n` +
      `Entry: ${entry || '-'}\n` +
      `Target: ${tp || '-'}\n` +
      `Stop:   ${sl || '-'}\n\n` +
      `Generated by AI @ TraderCopilot`;
  };

  const handleCopy = () => {
    const shareText = getShareText();
    if (navigator?.clipboard?.writeText) {
      navigator.clipboard.writeText(shareText);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    setSharing(true);
    const text = getShareText();
    try {
      await api.notifyTelegram(text, userProfile?.user?.telegram_chat_id);
      toast.success("Report sent to Telegram!");
    } catch (e) {
      console.error("Failed to share", e);
      toast.error("Failed to send report");
    } finally {
      setSharing(false);
    }
  };

  return (
    <div className="space-y-4 animate-in fade-in zoom-in duration-300">

      {/* Disclaimer / Header - only show if we have content */}
      {raw && raw.length > 0 && (
        <div className="flex justify-between items-center mb-2">
          <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-1">
            <FileText size={14} /> Institutional Report
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleShare}
              disabled={sharing}
              className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-sky-500/10 hover:text-sky-400 text-slate-400 text-xs font-bold rounded-lg transition-all border border-slate-700 hover:border-sky-500/50"
            >
              <Send size={14} />
              {sharing ? "Sending..." : "Telegram"}
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-lg transition-all shadow-lg hover:shadow-indigo-500/25"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? "Copied!" : "Copy Report"}
            </button>
          </div>
        </div>
      )}

      {/* ERROR / FALLBACK STATE: If raw text exists but no tags found, show raw as error/message */}
      {raw && !ctxt && !ta && !plan && !insight && (
        <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
          <h3 className="text-sm font-bold text-slate-400 mb-2">Analysis Output</h3>
          <p className="text-sm text-slate-300 whitespace-pre-wrap font-mono">
            {raw}
          </p>
        </div>
      )}

      {/* Grid Layout */}
      <div className="grid grid-cols-1 gap-4">

        {/* Context Card */}
        {ctxt && (
          <div className="bg-slate-900/50 border border-slate-800 p-4 rounded-xl relative overflow-hidden group hover:border-indigo-500/30 transition-colors">
            <div className="absolute top-0 right-0 p-4 text-slate-700 group-hover:text-indigo-500/20 transition-colors">
              <Globe size={48} strokeWidth={1} />
            </div>
            <h3 className="text-sm font-bold text-slate-200 mb-2 flex items-center gap-2">
              <Globe size={16} className="text-indigo-400" /> Market Context
            </h3>
            <p className="text-sm text-slate-400 leading-relaxed relative z-10 whitespace-pre-wrap">
              {ctxt?.replace(/\\n/g, '\n')}
            </p>
          </div>
        )}

        {/* Technical Analysis Card */}
        {ta && (
          <div className="bg-slate-900/50 border border-slate-800 p-4 rounded-xl relative overflow-hidden group hover:border-emerald-500/30 transition-colors">
            <div className="absolute top-0 right-0 p-4 text-slate-700 group-hover:text-emerald-500/20 transition-colors">
              <Activity size={48} strokeWidth={1} />
            </div>
            <h3 className="text-sm font-bold text-slate-200 mb-2 flex items-center gap-2">
              <Activity size={16} className="text-emerald-400" /> Technical Analysis
            </h3>
            <p className="text-sm text-slate-400 leading-relaxed relative z-10 whitespace-pre-wrap">
              {ta?.replace(/\\n/g, '\n')}
            </p>
          </div>
        )}

        {/* Plan Card */}
        {plan && (
          <div className="bg-gradient-to-br from-indigo-900/20 to-slate-900/50 border border-indigo-500/30 p-4 rounded-xl relative overflow-hidden">
            <h3 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
              <Target size={16} className="text-indigo-400" /> Execution Plan
            </h3>
            <p className="text-sm text-slate-300 leading-relaxed font-medium whitespace-pre-wrap">
              {plan?.replace(/\\n/g, '\n')}
            </p>
            {/* Embedded Params */}
            {(entry || tp || sl) && (
              <div className="mt-4 grid grid-cols-3 gap-2">
                <div className="bg-slate-950/50 rounded-lg p-2 text-center border border-slate-800">
                  <div className="text-[10px] text-slate-500 uppercase font-bold">Entry</div>
                  <div className="text-slate-200 font-mono font-bold">{entry || '-'}</div>
                </div>
                <div className="bg-emerald-900/20 rounded-lg p-2 text-center border border-emerald-900/30">
                  <div className="text-[10px] text-emerald-500 uppercase font-bold">TP</div>
                  <div className="text-emerald-400 font-mono font-bold">{tp || '-'}</div>
                </div>
                <div className="bg-rose-900/20 rounded-lg p-2 text-center border border-rose-900/30">
                  <div className="text-[10px] text-rose-500 uppercase font-bold">SL</div>
                  <div className="text-rose-400 font-mono font-bold">{sl || '-'}</div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Insight Card */}
        {insight && (
          <div className="bg-amber-900/10 border border-amber-900/30 p-4 rounded-xl flex gap-3">
            <div className="mt-1">
              <Lightbulb size={20} className="text-amber-400" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-amber-500 mb-1">Key Insight</h3>
              <p className="text-sm text-amber-200/80 leading-relaxed italic whitespace-pre-wrap">
                "{insight?.replace(/\\n/g, '\n')}"
              </p>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
