import React, { useMemo } from 'react';
import { Bot, Sparkles, Globe, Activity, Crosshair, Lightbulb, ListChecks } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

import { ShareMenu } from './common/ShareMenu';

interface ProAnalysisViewerProps {
  raw: any; // Can be string (legacy/fallback) or JSON object
  token: string;
}

export function ProAnalysisViewer({ raw, token }: ProAnalysisViewerProps) {
  const sections = useMemo(() => {
    if (!raw) return null;

    // A) Si es objeto JSON (Nueva estructura)
    if (typeof raw === 'object' && raw.context) {
      return {
        context: raw.context.summary, // + sentiment?
        technical: raw.technical.summary, // + key_levels?
        plan: raw.plan.strategy, // + management?
        insight: raw.insight.content,
        params: `Entry: ${raw.params.entry}\nTP: ${raw.params.tp}\nSL: ${raw.params.sl}`
      };
    }

    // B) Si es string (Legacy Markdown fallback)
    if (typeof raw === 'string') {
      const parse = (tag: string) => {
        const regex = new RegExp(`#${tag}#([\\s\\S]*?)(?=#|$)`, 'i');
        const match = raw.match(regex);
        return match ? match[1].trim() : null;
      };

      return {
        context: parse('CTXT'),
        technical: parse('TA'),
        plan: parse('PLAN'),
        insight: parse('INSIGHT'),
        params: parse('PARAMS'),
        fallback: raw.includes('#ANALYSIS_START') ? null : raw
      };
    }

    return null;
  }, [raw]);

  if (!raw) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-slate-500 opacity-50 animate-pulse">
        <Sparkles size={48} className="mb-4 text-slate-600" />
        <p className="font-mono text-sm">Initializing Neural Net...</p>
      </div>
    );
  }

  // Construct Share Text for Analysis
  const shareText = sections ? `🧠 *INSTITUTIONAL ANALYSIS: ${token}*

🌍 *MARKET CONTEXT*
${sections.context || 'N/A'}

📊 *TECHNICALS*
${sections.technical || 'N/A'}

🎯 *EXECUTION PLAN*
${sections.plan || 'N/A'}

🚀 *PARAMETERS*
${sections.params || 'N/A'}

💡 *INSIGHT*
${sections.insight || 'N/A'}

_Generated by TraderCopilot PRO_` : `Analysis for ${token}`;

  // Fallback for non-tagged responses (e.g. errors or legacy)
  if (sections?.fallback) {
    return (
      <div className="glass-card rounded-2xl p-6 lg:p-8 animate-in fade-in slide-in-from-bottom-5 duration-700">
        <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
          <Bot size={20} className="text-brand-400" /> Analysis Report
        </h3>
        <div className="prose prose-invert max-w-none text-slate-300">
          <ReactMarkdown>{sections.fallback}</ReactMarkdown>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-5 duration-700">

      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-brand-500/20">
            <Bot size={20} className="text-white" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              Institutional Report
              <span className="px-2 py-0.5 rounded-full bg-brand-500/10 border border-brand-500/20 text-[10px] text-brand-300 font-mono uppercase">PRO Agent</span>
            </h3>
            <p className="text-slate-400 text-xs font-mono tracking-wide">GENERATED FOR {token}</p>
          </div>
        </div>
        <ShareMenu
          title={`Analysis: ${token}`}
          text={shareText}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* Context Column */}
        <div className="space-y-6">
          {sections?.context && (
            <Card className="bg-black/20 border-white/10 overflow-hidden">
              <CardHeader className="bg-white/5 pb-3">
                <CardTitle className="text-sm font-bold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
                  <Globe size={16} className="text-blue-400" /> Market Context
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 text-slate-300 text-sm leading-relaxed">
                <ReactMarkdown>{sections.context}</ReactMarkdown>
              </CardContent>
            </Card>
          )}

          {sections?.insight && (
            <Card className="bg-gradient-to-br from-brand-900/10 to-indigo-900/10 border-brand-500/20">
              <CardHeader className="pb-3 border-b border-brand-500/10">
                <CardTitle className="text-sm font-bold text-brand-300 flex items-center gap-2 uppercase tracking-wider">
                  <Lightbulb size={16} className="text-brand-400" /> Key Insight
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 text-brand-100 text-sm italic font-medium leading-relaxed">
                <ReactMarkdown>{sections.insight}</ReactMarkdown>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Technical Column */}
        <div className="space-y-6">
          {sections?.technical && (
            <Card className="bg-black/20 border-white/10 h-full">
              <CardHeader className="bg-white/5 pb-3">
                <CardTitle className="text-sm font-bold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
                  <Activity size={16} className="text-emerald-400" /> Technical Analysis
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 text-slate-300 text-sm leading-relaxed space-y-2">
                <ReactMarkdown>{sections.technical}</ReactMarkdown>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Execution Plan (Full Width) */}
      {sections?.plan && (
        <Card className="bg-black/40 border-white/10">
          <CardHeader className="pb-3 border-b border-white/5">
            <CardTitle className="text-sm font-bold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
              <Crosshair size={16} className="text-rose-400" /> Execution Plan
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 text-slate-300 text-sm leading-relaxed grid md:grid-cols-2 gap-8">
            <div className="prose prose-invert prose-sm max-w-none">
              <ReactMarkdown>{sections.plan}</ReactMarkdown>
            </div>

            {/* Render Params if available */}
            {sections.params && (
              <div className="bg-gradient-to-br from-brand-900/20 to-black/40 rounded-xl p-0 border border-brand-500/20 overflow-hidden">
                <div className="px-4 py-3 border-b border-brand-500/10 bg-brand-500/5 flex items-center justify-between">
                  <div className="text-brand-300 text-xs font-bold uppercase tracking-widest flex items-center gap-2">
                    <ListChecks size={14} /> Confirmed Levels
                  </div>
                  <Badge variant="outline" className="border-brand-500/20 text-brand-400 text-[10px] bg-brand-500/5">
                    EXECUTION
                  </Badge>
                </div>

                <div className="p-4 grid grid-cols-3 gap-4">
                  {(() => {
                    // Simple Parser for Entry/TP/SL
                    const entryMatch = sections.params.match(/Entry:\s*([\d\.]+)/i);
                    const tpMatch = sections.params.match(/TP:\s*([\d\.]+)/i);
                    const slMatch = sections.params.match(/SL:\s*([\d\.]+)/i);

                    const entry = entryMatch ? entryMatch[1] : "N/A";
                    const tp = tpMatch ? tpMatch[1] : "N/A";
                    const sl = slMatch ? slMatch[1] : "N/A";

                    return (
                      <>
                        <div className="bg-black/20 rounded-lg p-3 border border-white/5 flex flex-col items-center justify-center text-center">
                          <span className="text-xs text-slate-500 uppercase font-mono mb-1">Entry Zone</span>
                          <span className="text-lg font-bold text-white font-mono tracking-tight">{entry}</span>
                        </div>
                        <div className="bg-emerald-500/10 rounded-lg p-3 border border-emerald-500/20 flex flex-col items-center justify-center text-center">
                          <span className="text-xs text-emerald-400 uppercase font-mono mb-1">Target (TP)</span>
                          <span className="text-lg font-bold text-emerald-300 font-mono tracking-tight">{tp}</span>
                        </div>
                        <div className="bg-rose-500/10 rounded-lg p-3 border border-rose-500/20 flex flex-col items-center justify-center text-center">
                          <span className="text-xs text-rose-400 uppercase font-mono mb-1">Stop (SL)</span>
                          <span className="text-lg font-bold text-rose-300 font-mono tracking-tight">{sl}</span>
                        </div>
                      </>
                    );
                  })()}
                </div>
                {/* Fallback for rationale or extra text in params if needed */}
                <div className="px-4 pb-4 pt-0">
                  <p className="text-[10px] text-slate-500 text-center font-mono">
                    * Risk management is mandatory.
                  </p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

    </div>
  );
}
